/*
 * This file was generated automatically by xsubpp version 1.9508 from the
 * contents of Debug.xs. Do not edit this file, edit Debug.xs instead.
 *
 *	ANY CHANGES MADE HERE WILL BE LOST!
 *
 */

#line 1 "Debug.xs"
#include "EXTERN.h"
#include "perl.h"
#include "XSUB.h"

#include "ppport.h"


#line 18 "Debug.c"

XS(XS_X3D__Debug_sv_dump); /* prototype to pass -Wmissing-prototypes */
XS(XS_X3D__Debug_sv_dump)
{
    dXSARGS;
    if (items != 1)
	Perl_croak(aTHX_ "Usage: X3D::Debug::sv_dump(value)");
    {
	SV*	value = ST(0);
#line 14 "Debug.xs"
  sv_dump(value);
#line 30 "Debug.c"
    }
    XSRETURN_EMPTY;
}

#ifdef __cplusplus
extern "C"
#endif
XS(boot_X3D__Debug); /* prototype to pass -Wmissing-prototypes */
XS(boot_X3D__Debug)
{
    dXSARGS;
    char* file = __FILE__;

    XS_VERSION_BOOTCHECK ;

        newXS("X3D::Debug::sv_dump", XS_X3D__Debug_sv_dump, file);
    XSRETURN_YES;
}

